### ISSUE TITLE
Free FW not work

### ISSUE THREAD

**Issue by Aliskin-Papa** [miksumin/ESP-Repo#1]
День добрый.

Котел Viessman Vitopend, ОТ шлюз от Игорь Мельник, контроллер Wemos Mini.

Прошивки от Игорь Мельник котел видят, управляют им.

Ваша прошивка никаких данных от котла не видит.
![Screenshot_20210430-145127_Chrome](https://user-images.githubusercontent.com/76951399/116692318-d5c3df80-a9c4-11eb-902e-d70fcb8f6efc.jpg)

**Comment by Aliskin-Papa** [comment]
Провода от котла подключены верно - т.к. светодиод на шлюзе мигает.

**Comment by miksumin** [comment]
Добрый день, проверьте правильность подключения адаптера к контроллеру: выход адаптера (входной сигнал контроллера от котла) - пин D1 (GPIO-05), вход адаптера (выходной сигнал контроллера на котел) - пин D2 (GPIO-04). В прошивках у Игоря Мельника подключение наоборот, т.е. вход контроллера - пин D2 (GPIO-04), выход контроллера  - пин D1 (GPIO-05).

**Comment by miksumin** [comment]
В папке \ESP-OT-Free прошивка ESP-OT-Free-IM.bin, собранная специально для вас, в которой подключения к контроллеру сделаны как у Игоря Мельника. Попробуйте, должно работать. Также обратите внимание, что после установления связи с котлом контроллеру требуется около 15 сек для опроса всех возможных DataID.

**Comment by Aliskin-Papa** [comment]
Добро, качаю и пробую, о результате отпишусь.

**Comment by Aliskin-Papa** [comment]
Да, новая прошивка частично помогла - пошел обмен данными с котлом, вижу/управляю:
- модуляция горелки - вижу
- температура DHW вижу/управляю
- температура CH/бойлер - вижу/не управляю
- статус шлюза - вижу On Line
- репорт ОТ - пусто
Запускал, рестартовал и шлюз/контроллер и котел. Ощущение, что выставлен малый интервал обмена по протоколу - светодиод шлюза мигает чаще, чем на прошивке от ИМ, гдето в 2-3 раза.
Прикладываю скрины:

![SmartSelect_20210430-213508_Chrome](https://user-images.githubusercontent.com/76951399/116742407-fbbaa580-a9ff-11eb-9013-2f9cd0d5b7c2.jpg)
![SmartSelect_20210430-214507_Chrome](https://user-images.githubusercontent.com/76951399/116742420-01b08680-aa00-11eb-9dee-0ca2f2e608fa.jpg)

**Comment by Aliskin-Papa** [comment]
![SmartSelect_20210430-214200_Chrome](https://user-images.githubusercontent.com/76951399/116742515-24db3600-aa00-11eb-8918-6640d1064f0d.jpg)

**Comment by miksumin** [comment]
По репорту моя ошибка, в попыхах добавил неправильное условие. Сейчас поправил, пересобрал, репорт должен работать.  обновлять прошивку можно через Update. По частоте мигания - все правильно, обмен идет без задержек в асинхронном режиме. Я правильно понял, что у вас управление температурой котла не работает? После первичного полного опроса котла (примерно 15 сек) обновите веб-страницу с информацией, должны появиться реальные пороги установки, в которых возможна регулировка температуры котла.

**Comment by Aliskin-Papa** [comment]
Да, правильно поняли - уставка на температуру СН не передается. На DHW передается в котел, а на обогрев (heating Taget) - нет.
Качаю, пробую, но отпишусь через часик (детей спать отбиваю).

**Comment by miksumin** [comment]
Посмотрите в репорте пороги установки температуры котла, возможно необходимо поправить верхний порог установки.

**Comment by miksumin** [comment]
Добавил отображение статуса сканирования котла и автообновление веб-страницы в процессе сканирования, загрузите последний вариант прошивки.

**Comment by Aliskin-Papa** [comment]
Добро, сейчас попробую.
С шаг назад прошивкой Репорт появился, вот результаты:
![SmartSelect_20210430-231508_Chrome](https://user-images.githubusercontent.com/76951399/116750247-d4b5a100-aa0a-11eb-9050-3d19ca45e42b.jpg)
![SmartSelect_20210430-231523_Chrome](https://user-images.githubusercontent.com/76951399/116750263-d97a5500-aa0a-11eb-8b41-16e5cc3572fc.jpg)

**Comment by Aliskin-Papa** [comment]
Уставка СН температуры не передается, т.е. передаются 5°С, но не та, которую ставишь.

**Comment by Aliskin-Papa** [comment]
Кстати, может поможет, вот то, чем я пользуюсь:

#include "esphome.h"
#include "esphome/components/sensor/sensor.h"
#include "OpenTherm.h"
#include "opentherm_switch.h"
#include "opentherm_climate.h"
#include "opentherm_binary.h"
#include "opentherm_output.h"


// Pins to OpenTherm Adapter
const int inPin = D2; 
const int outPin = D1; 

OpenTherm ot(inPin, outPin, false);

ICACHE_RAM_ATTR void handleInterrupt() {
	ot.handleInterrupt();
}

class OpenthermComponent: public PollingComponent {
private:
  const char *TAG = "opentherm_component";
  OpenthermFloatOutput *pid_output_;
public:
  Switch *thermostatSwitch = new OpenthermSwitch();
  Sensor *boiler_temperature = new Sensor();
  Sensor *modulation_sensor = new Sensor();
  Sensor *heatting_target_temperature_sensor = new Sensor();
  Climate *hotWaterClimate = new OpenthermClimate();
  OpenthermClimate *heatingWaterClimate = new OpenthermClimate();
  BinarySensor *flame = new OpenthermBinarySensor();
  
  // Set 3 sec. to give time to read all sensors (and not appear in HA as not available)
  OpenthermComponent(): PollingComponent(3000) {

  }

  void set_pid_output(OpenthermFloatOutput *pid_output) { pid_output_ = pid_output; }


  void setup() override {
    // This will be called once to set up the component
    // think of it as the setup() call in Arduino
      ESP_LOGD("opentherm_component", "Setup");

      ot.begin(handleInterrupt);

      thermostatSwitch->add_on_state_callback([=](bool state) -> void {
        ESP_LOGD ("opentherm_component", "termostatSwitch_on_state_callback %d", state);    
      });

      // Adjust HeatingWaterClimate depending on PID
      // heatingWaterClimate->set_supports_auto_mode(this->pid_output_ != nullptr);
      heatingWaterClimate->set_supports_two_point_target_temperature(this->pid_output_ != nullptr);
  }
  
  float getHotWaterTemperature() {
      unsigned long response = ot.sendRequest(ot.buildRequest(OpenThermRequestType::READ, OpenThermMessageID::Tdhw, 0));
      return ot.isValidResponse(response) ? ot.getFloat(response) : -1;
  }

  bool setHotWaterTemperature(float temperature) {
	    unsigned int data = ot.temperatureToData(temperature);
      unsigned long request = ot.buildRequest(OpenThermRequestType::WRITE, OpenThermMessageID::TdhwSet, data);
      unsigned long response = ot.sendRequest(request);
      return ot.isValidResponse(response);
  }

  float getModulation() {
    unsigned long response = ot.sendRequest(ot.buildRequest(OpenThermRequestType::READ, OpenThermMessageID::RelModLevel, 0));
    return ot.isValidResponse(response) ? ot.getFloat(response) : -1;
  }

  void update() override {

    ESP_LOGD("opentherm_component", "update");
    
    bool enableCentralHeating = heatingWaterClimate->mode == ClimateMode::CLIMATE_MODE_HEAT;
    bool enableHotWater = hotWaterClimate->mode == ClimateMode::CLIMATE_MODE_HEAT;
 
    //Set/Get Boiler Status
    auto response = ot.setBoilerStatus(enableCentralHeating, enableHotWater);
    bool isFlameOn = ot.isFlameOn(response);
    bool isCentralHeatingActive = ot.isCentralHeatingActive(response);
    float hotWater_temperature = getHotWaterTemperature();


    // Set temperature depending on room thermostat with/without PID
    float heatting_target_temperature;
    if (this->pid_output_ != nullptr) {
      float pid_output = pid_output_->get_state();
      if (pid_output == 0.0f) {
        heatting_target_temperature = 10.0f;
      }
      else {
        heatting_target_temperature =  pid_output * (heatingWaterClimate->target_temperature_high - heatingWaterClimate->target_temperature_low) 
        + heatingWaterClimate->target_temperature_low;      
      }
      ESP_LOGD("opentherm_component", "setBoilerTemperature  at %f °C (from PID Output)", heatting_target_temperature);
    }
    else if (thermostatSwitch->state) {
      heatting_target_temperature = heatingWaterClimate->target_temperature;
      ESP_LOGD("opentherm_component", "setBoilerTemperature  at %f °C (from heating water climate)", heatting_target_temperature);
    }
    else {
      // If the room thermostat is off, set it to 10, so that the pump continues to operate
      heatting_target_temperature = 10.0;
      ESP_LOGD("opentherm_component", "setBoilerTemperature at %f °C (default low value)", heatting_target_temperature);
    }
    ot.setBoilerTemperature(heatting_target_temperature);


    // Set hot water temperature
    setHotWaterTemperature(hotWaterClimate->target_temperature);

    // Read sensor values    
    float boilerTemperature = ot.getBoilerTemperature();
    float modulation = getModulation();

    // Publish sensor values
    flame->publish_state(isFlameOn); 
    boiler_temperature->publish_state(boilerTemperature);
    modulation_sensor->publish_state(modulation);
    heatting_target_temperature_sensor->publish_state(heatting_target_temperature);

    // Publish status of thermostat that controls hot water
    hotWaterClimate->current_temperature = hotWater_temperature;
    hotWaterClimate->action = isFlameOn ? ClimateAction::CLIMATE_ACTION_HEATING : ClimateAction::CLIMATE_ACTION_OFF;
    hotWaterClimate->publish_state();
    
    // Publish status of thermostat that controls heating
    heatingWaterClimate->current_temperature = boilerTemperature;
    heatingWaterClimate->action = isCentralHeatingActive && isFlameOn ? ClimateAction::CLIMATE_ACTION_HEATING : ClimateAction::CLIMATE_ACTION_OFF;
    heatingWaterClimate->publish_state();

  }

};

**Comment by miksumin** [comment]
DataID = 49 (Max CH water setpoint upper & lower bounds for adjustment) выдает нули, вот это очень странно. Может у вас там стоит какой нибудь ручной режим?

**Comment by miksumin** [comment]
Посмотрите вот это инфо - http://arduino.ru/forum/programmirovanie/termostat-opentherm-na-esp8266-dlya-viessmann-vitopend-100-w#comment-596091, там ссылка на видео, в котором говорят, что требуется изменить в режиме кодирования 1, параметр Р07 на 0. Посмотрите, что у вас стоит в настройках котла.

**Comment by Aliskin-Papa** [comment]
Неее, по Термостату из кода выше CH выдается какой поставишь, без проблем, проверяю прямо на лету на экране по сервис-кодам. А вот при старте контроллера с вашей прошивкой уставка сбрасывается на 5°С.
Вот:
![20210430_231227](https://user-images.githubusercontent.com/76951399/116751847-4bec3480-aa0d-11eb-808d-ded2924a034d.jpg)

**Comment by Aliskin-Papa** [comment]
> Посмотрите вот это инфо - http://arduino.ru/forum/programmirovanie/termostat-opentherm-na-esp8266-dlya-viessmann-vitopend-100-w#comment-596091, там ссылка на видео, в котором говорят, что требуется изменить в режиме кодирования 1, параметр Р07 на 0. Посмотрите, что у вас стоит в настройках котла.

Да, через это я уже неделю назад прошел - стояло по умолчанию 4 - ОТ в режиме термостата, сейчас стоит 0.

**Comment by miksumin** [comment]
Возможно, что у меня где-то в коде ошибка, посмотрю, но уже не сегодня. Вообще если у вас есть желание помочь мне отладить прошивку на вашем котле, напишите свои контакты мне на почту, чтобы можно было связаться напрямую.

**Comment by Aliskin-Papa** [comment]
С удовольствием не только помогу, но еще и материально готов оплатить ваш труд, т.к. сам в программировании только на уровне Бейсика......
А того, что мне нужно - у ИМ нету и на мой вопрос/просьбу сделать как нужно, он ответил "работаем, но не скоро".
Ваша почта в профиле есть?

**Comment by Aliskin-Papa** [comment]
Михаил, день добрый!
Как я понимаю, на эту почту можно писать?
Мой ВатсАп по номеру +79169163113

Алексей

пт, 30 апр. 2021 г., 17:53 Mikhail Sumin ***@***.***>:

**Comment by miksumin** [comment]
Моя почта есть в файле README. Свяжусь с вами в ближайшее время.

**Comment by miksumin** [comment]
Сделал вариант прошивки для вашего случая ESP-OT-Free-AL.bin, в котором верхняя граница установки берется из ID=57 (Max CH water setpoint), т.к. ID = 49 (Max CH water setpoint upper & lower bounds for adjustment) выдает нули. Попробуйте.

**Comment by miksumin** [comment]
Пересобрал ваш вариант прошивки с учетом того, что как я вижу в ответах у Viessmann байты данных перепутаны местами.
Проверьте и выложите пожалуйста репорт в текстовом виде.

**Comment by miksumin** [comment]
Доработал код прошивки, пересобрал и выложил ESP-OT-Free.bin. Проверьте пожалуйста, должно работать.
