### ISSUE TITLE
Связь с автором

### ISSUE THREAD

**Issue by taricru** [miksumin/ESP-Repo#3]
Добрый день, как с вами связаться по поводу приобретения конечного продукта?

**Comment by miksumin** [comment]
Добрый день, на основной странице описания в конце указан способ связи с автором, а именно:
Для связи с автором писать на почту [esp-ot@mail.ru](mailto:esp-ot@mail.ru)

**Comment by taricru** [comment]
Я туда писал, но ответа нет. Сейчас продублирую письмо. Спасибо!

**Comment by miksumin** [comment]
Уже ответил вам.

**Comment by miksumin** [comment]
Closed
